/**
 * AURA — Canonical Audit Action Types
 *
 * Source of truth: docs/03-API-CONTRACT.md §6.7
 *
 * ALL modules import from this file.
 * No module defines its own audit action constants.
 */

const AUDIT_ACTIONS = Object.freeze({
  TASK_CREATED: 'TASK_CREATED',
  PLAN_GENERATED: 'PLAN_GENERATED',
  PLAN_VALIDATED: 'PLAN_VALIDATED',
  PLAN_REJECTED: 'PLAN_REJECTED',
  STEP_STARTED: 'STEP_STARTED',
  TOOL_EXECUTED: 'TOOL_EXECUTED',
  TOOL_FAILED: 'TOOL_FAILED',
  APPROVAL_REQUESTED: 'APPROVAL_REQUESTED',
  APPROVAL_GRANTED: 'APPROVAL_GRANTED',
  APPROVAL_DENIED: 'APPROVAL_DENIED',
  STEP_COMPLETED: 'STEP_COMPLETED',
  STEP_FAILED: 'STEP_FAILED',
  REPLANNING: 'REPLANNING',
  VERIFICATION_STARTED: 'VERIFICATION_STARTED',
  VERIFICATION_PASSED: 'VERIFICATION_PASSED',
  VERIFICATION_FAILED: 'VERIFICATION_FAILED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  TASK_FAILED: 'TASK_FAILED',
  TASK_CANCELLED: 'TASK_CANCELLED',
  LLM_PROVIDER_FAILOVER: 'LLM_PROVIDER_FAILOVER',
});

/** All valid audit action values */
const ALL_AUDIT_ACTIONS = Object.freeze(Object.values(AUDIT_ACTIONS));

module.exports = {
  AUDIT_ACTIONS,
  ALL_AUDIT_ACTIONS,
};
